kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: base-im
  namespace: dev09
spec:
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/nodejs-12
      referencePolicy:
        type: Source

